# File: .github/workflows/ci.yml

name: PocketChef CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest
    timeout-minutes: 120

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Swift Package Manager dependencies
        uses: actions/cache@v4
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-spm-v2-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-v2-

      - name: Build for Testing
        run: |
          xcodebuild -project PocketChef.xcodeproj \
                     -scheme PocketChef \
                     -destination 'platform=iOS Simulator,name=iPhone 16 Pro' \
                     build-for-testing
                     
        - name: Run Unit Tests
        run: |
          xcodebuild -project PocketChef.xcodeproj \
                     -scheme PocketChef \
                     -destination 'platform=iOS Simulator,name=iPhone 16 Pro' \
                     test-without-building
